In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data/mustard++_text.csv")

In [3]:
len(data)

6041

In [4]:
scene_last_df = data.groupby("SCENE").last()

In [5]:
len(scene_last_df)

1202

In [6]:
scene_last_df

,KEY,SENTENCE,END_TIME,SPEAKER,SHOW,Sarcasm,Sarcasm_Type,Implicit_Emotion,Explicit_Emotion,Valence,Arousal
SCENE,,,,,,,,,,,
1_10004,1_10004_u,"And of those few months, how long have you bee...",0:07,SHELDON,BBT,0.0,NONE,Anger,Anger,2.0,7.0
1_10009,1_10009_u,"Let the dead man talk. So, why do you think that?",0:05,PENNY,BBT,0.0,NONE,Happiness,Happiness,6.0,5.0
1_1001,1_1001_u,"What else? Sell it on eBay as ""slightly used.""",0:04,RAJ,BBT,0.0,NONE,Excitement,Excitement,6.0,5.0
1_1003,1_1003_u,"Good idea, sit with her. Hold her, comfort her...",0:08,HOWARD,BBT,1.0,PRO,Anger,Sadness,3.0,6.0
1_10190,1_10190_u,"Well, now that I've given up string theory, I'...",0:11,SHELDON,BBT,0.0,NONE,Neutral,Neutral,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
3_S06E02_398,3_S06E02_398_u,"Look, we cannot take blood money.",0:02.166000,OTHER,SV,0.0,NONE,Sadness,Disgust,3.0,7.0
3_S06E03_366,3_S06E03_366_u,The-the same way we can buy America and everyt...,0:2.542,RICHARD,SV,1.0,PRO,Ridicule,Neutral,4.0,6.0
3_S06E05_355,3_S06E05_355_u,"Well, maybe some time when you're working on s...",0:10.04199,OTHER,SV,1.0,PRO,Frustration,Frustration,3.0,7.0
3_S06E06_143,3_S06E06_143_u,I thought that was the company policy-these days.,0:4.459000,GILFOYLE,SV,1.0,ILL,Frustration,Neutral,4.0,7.0
3_S06E07_272,3_S06E07_272_u,That you're an alcoholic?,0:1.459000,DINESH,SV,1.0,ILL,Ridicule,Surprise,4.0,6.0

In [7]:
scene_last_df = scene_last_df.drop(columns=['SENTENCE', 'END_TIME', 'Implicit_Emotion', 'Explicit_Emotion', 'Valence', 'Arousal'])

In [8]:
scene_last_df.to_csv("data/scene_labels.csv")

In [9]:
scene_last_df.head(5)

               KEY  SPEAKER SHOW  Sarcasm Sarcasm_Type
SCENE
1_10004  1_10004_u  SHELDON  BBT      0.0         NONE
1_10009  1_10009_u    PENNY  BBT      0.0         NONE
1_1001    1_1001_u      RAJ  BBT      0.0         NONE
1_1003    1_1003_u   HOWARD  BBT      1.0          PRO
1_10190  1_10190_u  SHELDON  BBT      0.0         NONE