In [1]:
import pandas as pd
from sklearn.metrics import classification_report

In [2]:
audio_pred = pd.read_csv("audio_predictions.csv")
lexical_pred = pd.read_csv("lexical_predictions.csv")
visual_pred = pd.read_csv("visual_predictions.csv")

In [3]:
audio_pred.head()

          scene  audio_predictions  actuals
0         2_388                  1        0
1        1_5058                  1        1
2  1_S11E21_080                  1        1
3  1_S11E12_038                  1        1
4  1_S11E01_337                  1        0

In [4]:
lexical_pred.head()

          scene  lexical_predictions  actuals
0         2_388                    1        0
1        1_5058                    1        1
2  1_S11E21_080                    1        1
3  1_S11E12_038                    1        1
4  1_S11E01_337                    0        0

In [5]:
visual_pred.head()

     scene  visual_predictions  actuals
0  1_10009                   1        0
1   1_1003                   1        1
2    1_105                   0        1
3  1_10797                   1        0
4  1_10890                   1        1

In [6]:
merged = pd.merge(audio_pred[["scene", "actuals", "audio_predictions"]], lexical_pred[["scene", "lexical_predictions"]], how = 'left', on = "scene")
merged = pd.merge(merged, visual_pred[["scene", "visual_predictions"]])

In [7]:
merged.head()

,scene,actuals,audio_predictions,lexical_predictions,visual_predictions
0,2_388,0,1,1,1
1,1_5058,1,1,1,1
2,1_S11E21_080,1,1,1,1
3,1_S11E12_038,1,1,1,0
4,1_S11E01_337,0,1,0,1

In [8]:
merged["aud_lex_vid_mode_pred"] = merged.filter(like='_predictions').mode(axis=1)

In [9]:
merged["aud_lex_vid_or_pred"] = merged["audio_predictions"] | merged["lexical_predictions"] | merged["visual_predictions"]

In [10]:
merged["aud_lex_vid_and_pred"] = merged["audio_predictions"] & merged["lexical_predictions"] & merged["visual_predictions"]

In [11]:
merged.head(50)

,scene,actuals,audio_predictions,lexical_predictions,visual_predictions,aud_lex_vid_mode_pred,aud_lex_vid_or_pred,aud_lex_vid_and_pred
0,2_388,0,1,1,1,1,1,1
1,1_5058,1,1,1,1,1,1,1
2,1_S11E21_080,1,1,1,1,1,1,1
3,1_S11E12_038,1,1,1,0,1,1,0
4,1_S11E01_337,0,1,0,1,1,1,0
5,2_342,1,1,1,1,1,1,1
6,1_S10E10_009,1,1,1,0,1,1,0
7,1_11021,1,1,1,1,1,1,1
8,1_S10E07_110,1,1,1,1,1,1,1
9,1_S09E04_207,0,0,0,0,0,0,0
10,2_475,1,1,1,1,1,1,1
11,2_180,0,0,0,0,0,0,0
12,2_232,0,0,0,0,0,0,0
13,2_415,0,0,0,0,0,0,0
14,1_S11E05_193,1,0,1,1,1,1,0
15,2_611,1,1,0,0,0,1,0
16,3_S06E02_171,0,1,0,0,0,1,0
17,1_S10E18_164,1,1,0,1,1,1,0
18,2_474,1,0,1,0,0,1,0
19,2_310,1,1,1,1,1,1,1
20,1_5212,0,0,1,1,1,1,0
21,1_S12E03_174,0,0,0,0,0,0,0
22,2_585,0,0,0,0,0,0,0
23,3_S01E03_024,0,0,1,0,0,1,0
24,1_7395,1,1,1,1,1,1,1
25,2_96,0,0,1,1,1,1,0
26,2_97,1,0,0,0,0,0,0
27,1_S11E11_055,0,0,1,0,0,1,0
28,2_190,1,1,0,1,1,1,0
29,1_9003,0,0,0,0,0,0,0
30,2_48,0,0,0,1,0,1,0
31,1_6860,0,0,0,0,0,0,0
32,2_392,1,1,1,1,1,1,1
33,1_3707,1,1,0,1,1,1,0
34,1_S12E06_367,0,0,0,1,0,1,0
35,1_3837,0,1,0,1,1,1,0
36,2_344,1,1,0,1,1,1,0
37,1_6211,0,1,0,1,1,1,0
38,2_507,1,1,1,1,1,1,1
39,1_3599,0,1,0,1,1,1,0
40,1_S12E05_054,0,0,1,1,1,1,0
41,1_10009,0,0,0,1,0,1,0
42,1_S11E10_143,0,1,0,0,0,1,0
43,2_124,1,1,1,1,1,1,1
44,3_S02E10_133,1,1,0,1,1,1,0
45,2_393,0,0,1,1,1,1,0
46,2_245,0,0,0,1,0,1,0
47,1_S12E21_285,1,1,0,1,1,1,0
48,1_6627,0,1,0,1,1,1,0
49,2_318,1,0,1,0,0,1,0

### ### Audio - Lexical - Visual Mode

In [12]:
print(classification_report(merged['actuals'], merged["aud_lex_vid_mode_pred"], digits=4))

              precision    recall  f1-score   support

           0     0.7404    0.6364    0.6844       121
           1     0.6788    0.7750    0.7237       120

    accuracy                         0.7054       241
   macro avg     0.7096    0.7057    0.7041       241
weighted avg     0.7097    0.7054    0.7040       241

### Audio - Lexical - Visual OR

In [13]:
print(classification_report(merged['actuals'], merged["aud_lex_vid_or_pred"], digits=4))

              precision    recall  f1-score   support

           0     0.8667    0.3223    0.4699       121
           1     0.5816    0.9500    0.7215       120

    accuracy                         0.6349       241
   macro avg     0.7241    0.6362    0.5957       241
weighted avg     0.7247    0.6349    0.5952       241

### Audio - Lexical - Visual AND

In [14]:
print(classification_report(merged['actuals'], merged["aud_lex_vid_and_pred"], digits=4))

              precision    recall  f1-score   support

           0     0.6474    0.9256    0.7619       121
           1     0.8676    0.4917    0.6277       120

    accuracy                         0.7095       241
   macro avg     0.7575    0.7086    0.6948       241
weighted avg     0.7571    0.7095    0.6951       241